// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250410154232_AddTable")]
    partial class AddTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Group", b =>
                {
                    b.Property<int>("PK_VehicleGroupID")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedByUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<double?>("DistanceA")
                        .HasColumnType("float");

                    b.Property<double?>("DistanceB")
                        .HasColumnType("float");

                    b.Property<int?>("FK_BGTProvinceID")
                        .HasColumnType("int");

                    b.Property<int>("FK_CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MinuteA")
                        .HasColumnType("int");

                    b.Property<int?>("MinuteB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ParentVehicleGroupID")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedByUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PK_VehicleGroupID");

                    b.ToTable("Vehicle.Groups", "dbo");
                });

            modelBuilder.Entity("API.Entities.Vehicle", b =>
                {
                    b.Property<long>("PK_VehicleID")
                        .HasColumnType("bigint");

                    b.Property<int>("FK_CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("IMEI")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsCam")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVideoCam")
                        .HasColumnType("bit");

                    b.Property<string>("PrivateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("XNCode")
                        .HasColumnType("int");

                    b.HasKey("PK_VehicleID");

                    b.ToTable("Vehicle.Vehicles", "dbo");
                });

            modelBuilder.Entity("API.Entities.VehicleGroup", b =>
                {
                    b.Property<int>("FK_VehicleGroupID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FK_VehicleID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("FK_CompanyID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("FK_VehicleGroupID", "FK_VehicleID");

                    b.ToTable("Vehicle.VehicleGroups", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
